name: first-workflow
on:
  push:
    branches:
      - main
jobs:
  First-Job:
    name: First-Job
    runs-on: ubuntu-latest
    steps:
      - name: Before
        run: ls
        shell: bash

      - name: checkout
        uses: actions/checkout@v3

      - name: After
        run: ls
        shell: bash
